name: default

on: [push]

jobs:
  default:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: setup python 
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: setup requirements
        run: |
          pip install -r requirements.txt

      - uses: dmpetrov/dvc-action-test@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dvc_repro_file: eval.dvc
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

